---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/helm
inputs:
- name: gcp-service-broker
  path: broker-source
- name: metadata
outputs:
- name: helm-chart
run:
  path: gcp-service-broker-ci/ci/tasks/bundle.sh
